apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ozgurozturknet/k8s:blue
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# Liveness probes are a mechanism provided by Kubernetes which helps determine 
# if applications running within containers are operational.
# This can help improve resilience and availability for Kubernetes pods.     
# Yani Liveness probes container'daki uygulamaların çalışır durumda olup olmadığını belirlemeye çalışır.    
     
# Readiness sayaesinde podun hem başta hemde sonda trafik almaya hazır olup olmadığını    
# kontrol ederek servisin endpointinden ekleyip çıkarta biliriz.     
     
# The initialDelaySeconds field tells the kubelet that 
# it should wait 5 seconds before performing the first probe.
      