apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo
spec:
  selector:
    app: demo 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
    nodePort: 30001 